version: 1.0.{build}
before_build:
- git clone https://github.com/LukasBanana/GaussianLib.git
- cmake -G "Visual Studio 14 2015" -DGaussianLib_INCLUDE_DIR:STRING="GaussianLib/include"
build:
  project: LLGL.sln